[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && cd python_version && python manage.py collectstatic --noinput && python manage.py migrate"

[deploy]
startCommand = "gunicorn --chdir python_version expense_tracker.wsgi --bind 0.0.0.0:$PORT"
